services:

  aws:
    image: amazon/aws-cli
    volumes:
      - .:/code
      - aws-credentials:/root/.aws
    restart: "no"
    working_dir: /code
    entrypoint: aws
    environment:
      AWS_PROFILE: ${TF_VAR_AWS_PROFILE}

  terraform:
    image: mssms1/terraform:terraform_${TERRAFORM_VERSION}--awscli_${AWS_CLI_VERSION}--helm_${HELM_VERSION}
    build:
      context: ./terraform_image
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION}
        HELM_VERSION: ${HELM_VERSION}
    volumes:
      - .:/code
      - aws-credentials:/root/.aws
    working_dir: /code
    environment:
      TF_VAR_AWS_PROFILE: ${TF_VAR_AWS_PROFILE}

  kubectl:
    image: mssms1/kubectl:kubectl_${KUBECTL_VERSION}--awscli_${AWS_CLI_VERSION}--helm_${HELM_VERSION}
    build:
      context: ./kubectl_image
      args:
        KUBECTL_VERSION: ${KUBECTL_VERSION}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION}
        HELM_VERSION: ${HELM_VERSION}
    restart: "no"
    working_dir: /code
    volumes:
      - .:/code
      - aws-credentials:/root/.aws:ro
    entrypoint: kubectl
    environment:
      AWS_PROFILE: ${TF_VAR_AWS_PROFILE}

volumes:
  aws-credentials:
    name: aws-credentials
    external: true
  